#!/usr/bin/env bash

sh -c 'echo "CREATE USER ${DB_ORTHANC_USER} WITH PASSWORD '\''${DB_ORTHANC_PASSWORD}'\'';" | exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U ${DB_SUPER_USER}'
sh -c 'echo "CREATE DATABASE ${DB_ORTHANC_NAME} WITH OWNER ${DB_ORTHANC_USER};" | exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U ${DB_SUPER_USER}'

#echo "CREATE USER ${DB_ORTHANC_USER} WITH PASSWORD '\''${DB_ORTHANC_PASSWORD}'\'';" | exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U ${DB_SUPER_USER}
#echo "CREATE DATABASE ${DB_ORTHANC_NAME} WITH OWNER ${DB_ORTHANC_USER};" | exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U ${DB_SUPER_USER}
