#!/usr/bin/env bash

export DB_NAME="orthanc"

sh -c 'echo "CREATE USER ${DB_USER} WITH PASSWORD '\''${DB_PASSWORD}'\'';" | exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U ${POSTGRES_USER}'
sh -c 'echo "CREATE DATABASE ${DB_NAME} WITH OWNER ${DB_USER};" | exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U ${POSTGRES_USER}'
