#!/usr/bin/env bash

export ORTHANC_DB_NAME="orthanc"

sh -c 'echo "CREATE USER ${POSTGRES_CIRR_USER} WITH PASSWORD '\''${POSTGRES_CIRR_PASSWORD}'\'';" | exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U ${POSTGRES_USER}'
sh -c 'echo "CREATE DATABASE ${ORTHANC_DB_NAME} WITH OWNER ${POSTGRES_CIRR_USER};" | exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U ${POSTGRES_USER}'
